@startuml
title Edit Player Profile

actor Player
database Client

Player->Client: Click Profile Button
Client->Player: Show Profile
Player->Client: Click Edit Profile Button
Player->Client: Change Name
Player->Client: Change Color
Player->Client: Click Edit Profile Button
Client->Client: Save Profile on Disk
Client->Player: Show Profile

@enduml